"use client";

import { useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, FileSpreadsheet, FileUp, Loader2, ShieldCheck, UploadCloud } from "lucide-react";
import { toast } from "sonner";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Select } from "@/components/ui/field";
import { useFinance } from "@/features/finance/finance-provider";
import { parseStatement } from "@/features/imports/pipeline";
import type { NormalizedTransaction } from "@/features/imports/types";
import { categorizeMerchant, detectDuplicates } from "@/features/finance/detection";

export default function ImportsPage() {
  const { data, addTransaction } = useFinance(); const input = useRef<HTMLInputElement>(null); const [rows, setRows] = useState<NormalizedTransaction[]>([]); const [filename, setFilename] = useState(""); const [accountId, setAccountId] = useState(data.accounts[0]?.id ?? ""); const [busy, setBusy] = useState(false);
  const pick = async (file?: File) => { if (!file) return; setBusy(true); try { const parsed = await parseStatement(file); const reviewed = parsed.map((row) => { if (row.issue) return row; const match = detectDuplicates({ accountId, amount: row.amount, date: row.date, merchant: row.merchant, type: row.direction === "credit" ? "income" : "expense", source: row.source === "txt" ? "csv" : row.source }, data.transactions)[0]; return match ? { ...row, issue: `${match.confidence === "likely" ? "Likely" : "Possible"} duplicate`, selected: false } : row; }); setRows(reviewed); setFilename(file.name); toast.success(`${parsed.length} rows normalized for review`); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not parse statement"); } finally { setBusy(false); } };
  const importSelected = async () => { const selected = rows.filter((row) => row.selected && !row.issue); if (!selected.length) return toast.error("Select at least one valid row"); setBusy(true); let imported = 0; try { for (const row of selected) { await addTransaction({ accountId, amount: row.amount, date: row.date, merchant: row.merchant, notes: row.description, type: row.direction === "credit" ? "income" : "expense", categoryId: categorizeMerchant(row.merchant), source: row.source === "txt" ? "csv" : row.source }); imported++; } setRows((current) => current.filter((row) => !row.selected)); toast.success(`${imported} transactions imported`); } catch (error) { toast.error(`Imported ${imported}; stopped because ${error instanceof Error ? error.message : "of an error"}`); } finally { setBusy(false); } };
  return <><PageHeading eyebrow="Bring your history" title="Import statements" description="Normalize, detect duplicates, categorize, and review before anything is saved." />
    {!rows.length ? <Card className="border-dashed"><CardContent className="grid place-items-center px-5 py-16 text-center sm:py-24"><span className="grid size-16 place-items-center rounded-3xl bg-accent text-brand"><UploadCloud className="size-7" /></span><h2 className="mt-6 text-xl font-bold">Drop in a bank statement</h2><p className="mt-2 max-w-md text-sm leading-6 text-muted">CSV, TXT, and XLSX are parsed locally in your browser. You will review every row before import.</p><input ref={input} className="sr-only" type="file" accept=".csv,.txt,.xlsx" onChange={(event) => void pick(event.target.files?.[0])}/><div className="mt-6 flex flex-wrap justify-center gap-2"><Button onClick={() => input.current?.click()} disabled={busy}>{busy ? <Loader2 className="size-4 animate-spin"/> : <FileUp className="size-4"/>}{busy ? "Reading..." : "Choose statement"}</Button></div><div className="mt-8 flex items-center gap-2 rounded-full bg-canvas px-4 py-2 text-[11px] font-semibold text-muted"><ShieldCheck className="size-3.5 text-positive"/>Nothing is saved until you confirm</div></CardContent></Card> : <>
      <Card className="mb-4"><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><span className="grid size-11 place-items-center rounded-2xl bg-accent text-brand"><FileSpreadsheet className="size-5"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{filename}</p><p className="text-xs text-muted">{rows.length} rows · {rows.filter((r) => r.issue).length} need review</p></div><label className="text-xs font-bold">Import to <Select className="ml-2 inline-flex w-48" value={accountId} onChange={(e) => setAccountId(e.target.value)}>{data.accounts.map((account) => <option value={account.id} key={account.id}>{account.name}</option>)}</Select></label></div></Card>
      <Card className="overflow-hidden"><div className="flex items-center justify-between border-b p-4 sm:p-5"><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={rows.filter((r) => !r.issue).every((r) => r.selected)} onChange={(e) => setRows((current) => current.map((row) => row.issue ? row : { ...row, selected: e.target.checked }))}/> Select all valid</label><Button onClick={importSelected} disabled={busy}>{busy ? <Loader2 className="size-4 animate-spin"/> : <CheckCircle2 className="size-4"/>}Import {rows.filter((r) => r.selected && !r.issue).length}</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-canvas text-[10px] uppercase tracking-wider text-muted"><tr><th className="p-3.5"></th><th className="p-3.5">Date</th><th className="p-3.5">Description</th><th className="p-3.5">Direction</th><th className="p-3.5 text-right">Amount</th><th className="p-3.5">Review</th></tr></thead><tbody>{rows.map((row) => <tr className="border-t" key={row.id}><td className="p-3.5"><input type="checkbox" disabled={Boolean(row.issue)} checked={row.selected} onChange={(e) => setRows((current) => current.map((item) => item.id === row.id ? { ...item, selected: e.target.checked } : item))}/></td><td className="p-3.5 font-semibold">{row.date || "—"}</td><td className="max-w-sm p-3.5"><p className="truncate font-bold">{row.merchant}</p><p className="truncate text-muted">{row.description}</p></td><td className="p-3.5 capitalize">{row.direction}</td><td className="amount p-3.5 text-right font-bold">₹{row.amount || "—"}</td><td className="p-3.5">{row.issue ? <span className="inline-flex items-center gap-1.5 rounded-full bg-negative/10 px-2 py-1 font-bold text-negative"><AlertTriangle className="size-3"/>{row.issue}</span> : <span className="inline-flex items-center gap-1.5 text-positive"><CheckCircle2 className="size-3"/>Ready</span>}</td></tr>)}</tbody></table></div></Card>
    </>}
  </>;
}
