"use client";

import { useState } from "react";
import { ChevronLeft, ChevronRight, CreditCard, HandCoins } from "lucide-react";
import { addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, startOfMonth, startOfWeek, subMonths } from "date-fns";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useFinance } from "@/features/finance/finance-provider";
import { formatMoney, sumMoney } from "@/features/finance/money";
import { TransactionRow } from "@/features/transactions/transaction-row";
import { accountDueDate } from "@/features/finance/liability-reminders";

export default function CalendarPage() {
  const { data } = useFinance(); const [month, setMonth] = useState(new Date()); const [selected, setSelected] = useState(new Date()); const days = eachDayOfInterval({ start: startOfWeek(startOfMonth(month), { weekStartsOn: 1 }), end: endOfWeek(endOfMonth(month), { weekStartsOn: 1 }) }); const selectedTx = data.transactions.filter((item) => isSameDay(new Date(`${item.date}T12:00:00`), selected));
  const liabilityEvents = data.accounts.filter((account) => !account.archived && account.liabilityStatus !== "closed" && account.liabilityStatus !== "paused" && account.remindersEnabled !== false && (account.type === "credit_card" || account.type === "loan")).flatMap((account) => {
    const due = accountDueDate(account, startOfMonth(month));
    return due && isSameMonth(due, month) ? [{ account, due, amountMinor: account.type === "loan" ? account.emiMinor : account.minimumPaymentMinor }] : [];
  });
  const selectedLiabilities = liabilityEvents.filter((item) => isSameDay(item.due, selected));
  return <><PageHeading eyebrow="Financial calendar" title={format(month, "MMMM yyyy")} description="See spending, income, bills, and repeating events in context." action={<div className="flex gap-2"><Button variant="secondary" size="icon" onClick={() => setMonth(subMonths(month,1))}><ChevronLeft className="size-4"/></Button><Button variant="secondary" onClick={() => setMonth(new Date())}>Today</Button><Button variant="secondary" size="icon" onClick={() => setMonth(addMonths(month,1))}><ChevronRight className="size-4"/></Button></div>}/>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><Card className="overflow-hidden"><div className="grid grid-cols-7 border-b bg-canvas/60">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((day) => <div key={day} className="py-3 text-center text-[10px] font-bold uppercase tracking-wider text-muted">{day}</div>)}</div><div className="grid grid-cols-7">{days.map((day) => { const transactions = data.transactions.filter((item) => isSameDay(new Date(`${item.date}T12:00:00`), day)); const expenses = sumMoney(transactions.filter((item) => item.type === "expense").map((item) => item.amountMinor)); const income = sumMoney(transactions.filter((item) => item.type === "income").map((item) => item.amountMinor)); const hasLiabilityDue = liabilityEvents.some((item) => isSameDay(item.due, day)); return <button key={day.toISOString()} onClick={() => setSelected(day)} className={`min-h-20 border-b border-r p-2 text-left transition hover:bg-canvas sm:min-h-28 sm:p-3 ${!isSameMonth(day, month) ? "opacity-35" : ""} ${isSameDay(day, selected) ? "bg-accent/50" : ""}`}><span className={`grid size-6 place-items-center rounded-full text-xs font-bold ${isSameDay(day,new Date()) ? "bg-brand text-white" : ""}`}>{format(day,"d")}</span><div className="mt-2 space-y-1 text-[9px] font-bold sm:text-[10px]">{hasLiabilityDue && <p className="truncate text-warning">Payment due</p>}{expenses > 0n && <p className="truncate text-expense">−{formatMoney(expenses, data.profile.currency, "en-IN", true)}</p>}{income > 0n && <p className="truncate text-income">+{formatMoney(income, data.profile.currency, "en-IN", true)}</p>}</div></button>; })}</div></Card>
      <div className="grid content-start gap-5"><Card><div className="border-b p-5"><p className="eyebrow">Selected day</p><h2 className="mt-2 text-xl font-bold">{format(selected,"d MMMM, EEEE")}</h2></div><CardContent className="px-5 py-1">{selectedLiabilities.map(({ account, amountMinor }) => <div key={account.id} className="flex items-center gap-3 border-b border-border py-4"><span className="grid size-10 place-items-center rounded-xl bg-warning/10 text-warning">{account.type === "loan" ? <HandCoins className="size-5" /> : <CreditCard className="size-5" />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{account.name}</p><p className="text-xs text-muted-foreground">{account.type === "loan" ? "EMI due" : "Card payment due"}</p></div>{amountMinor !== undefined && <strong className="amount text-sm">{formatMoney(amountMinor, data.profile.currency)}</strong>}</div>)}{selectedTx.map((item) => <TransactionRow key={item.id} transaction={item} accounts={data.accounts} categories={data.categories} compact />)}{!selectedTx.length && !selectedLiabilities.length && <div className="py-14 text-center text-sm text-muted">No activity on this day.</div>}</CardContent></Card>{data.notifications.length > 0 && <Card><div className="border-b p-5"><p className="eyebrow">Notifications</p><h2 className="mt-2 text-lg font-bold">Payment reminders</h2></div><CardContent className="divide-y divide-border px-5 py-1">{data.notifications.slice(0, 5).map((notification) => <div key={notification.id} className="py-4"><p className="text-sm font-semibold">{notification.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{notification.body}</p></div>)}</CardContent></Card>}</div></div>
  </>;
}
