"use client";

import { ArrowDownRight, ArrowUpRight, BadgeIndianRupee, TrendingUp } from "lucide-react";
import { endOfMonth, startOfMonth } from "date-fns";
import { PageHeading } from "@/components/page-heading";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useFinance } from "@/features/finance/finance-provider";
import { monthlySummary, spendingByCategory, transactionsInRange } from "@/features/finance/calculations";
import { formatMoney, percentage } from "@/features/finance/money";
import { CategoryBars } from "@/features/insights/category-bars";
import { CashflowChart } from "@/features/dashboard/cashflow-chart";

export default function InsightsPage() {
  const { data } = useFinance(); const now = new Date(); const current = transactionsInRange(data.transactions, startOfMonth(now), endOfMonth(now)); const summary = monthlySummary(data.transactions, now); const groups = spendingByCategory(current); const largest = [...current].filter((item) => item.type === "expense").sort((a,b) => a.amountMinor === b.amountMinor ? 0 : a.amountMinor > b.amountMinor ? -1 : 1)[0];
  return <><PageHeading eyebrow="Deterministic analysis" title="Insights" description="The numbers below are calculated from your transactions—not generated by AI." />
    <div className="mb-5 grid gap-4 md:grid-cols-3"><Insight label="Savings rate" value={`${summary.savingsRate.toFixed(1)}%`} note={`${formatMoney(summary.savings, data.profile.currency)} saved`} icon={TrendingUp}/><Insight label="Month over month" value={`${summary.spendingChange > 0 ? "+" : ""}${summary.spendingChange.toFixed(1)}%`} note="Change in net spending" icon={summary.spendingChange > 0 ? ArrowUpRight : ArrowDownRight} negative={summary.spendingChange > 0}/><Insight label="Largest expense" value={formatMoney(largest?.amountMinor ?? 0n, data.profile.currency)} note={largest?.merchant ?? "No expenses"} icon={BadgeIndianRupee}/></div>
    <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><div><p className="eyebrow mb-1.5">This month</p><CardTitle>Category spending</CardTitle></div></CardHeader><CardContent><CategoryBars transactions={current} categories={data.categories} currency={data.profile.currency}/></CardContent></Card><Card><CardHeader><div><p className="eyebrow mb-1.5">Last 6 months</p><CardTitle>Income vs spending</CardTitle></div></CardHeader><CardContent><CashflowChart transactions={data.transactions} currency={data.profile.currency}/></CardContent></Card></div>
    <Card className="mt-5"><CardHeader><div><p className="eyebrow mb-1.5">Ranked</p><CardTitle>Category detail</CardTitle></div></CardHeader><CardContent className="pt-1">{groups.map((item, index) => { const cat = data.categories.find((entry) => entry.id === item.categoryId); return <div key={item.categoryId} className="grid grid-cols-[28px_1fr_auto] items-center gap-3 border-b py-4 last:border-0"><span className="text-xs font-bold text-muted">{String(index+1).padStart(2,"0")}</span><div><div className="flex justify-between text-sm"><span className="font-bold">{cat?.name ?? "Other"}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-canvas"><div className="h-full rounded-full" style={{ width: `${percentage(item.amountMinor, summary.expenses)}%`, background: cat?.color }}/></div></div><strong className="amount text-sm">{formatMoney(item.amountMinor, data.profile.currency)}</strong></div>; })}</CardContent></Card>
  </>;
}
function Insight({ label, value, note, icon: Icon, negative }: { label:string; value:string; note:string; icon:typeof TrendingUp; negative?:boolean }) { return <Card><CardContent className="flex items-start justify-between p-5 sm:p-6"><div><p className="eyebrow">{label}</p><p className={`amount mt-3 text-2xl font-extrabold ${negative ? "text-expense" : ""}`}>{value}</p><p className="mt-1 text-xs text-muted">{note}</p></div><span className={`grid size-10 place-items-center rounded-xl ${negative ? "bg-expense/10 text-expense" : "bg-accent text-brand"}`}><Icon className="size-4"/></span></CardContent></Card>; }
